# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
ZSH_HIGHLIGHT_STYLES[alias]="fg=109"
ZSH_HIGHLIGHT_STYLES[arg0]="fg=109"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=246"
ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=209"
ZSH_HIGHLIGHT_STYLES[path]="fg=140,underline"
ZSH_HIGHLIGHT_STYLES[default]="fg=140"
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=140"
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=140"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=143"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=143"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
POWERLEVEL9K_DIR_FOREGROUND=233
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=233
POWERLEVEL9K_SHORTEN_STRATEGY=default